version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_php_app
    ports:
      - "9090:80"
    volumes:
      - /root/app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
    user: root

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_fpm_app
    volumes:
      - /root/app:/var/www/html
    networks:
      - app-network
    user: root

  mysql:
    image: mysql:8.0
    container_name: mysql_app
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: u184945698_sig
      MYSQL_USER: user_app
      MYSQL_PASSWORD: password123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
